[package]
name = "win"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["std", "winerror", "errhandlingapi", "psapi", "handleapi", "processthreadsapi", "winnt", "minwindef", "memoryapi", "libloaderapi", "synchapi", "winbase"] }
lazy_static = "1.4.0"
